name: Rust
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: hprof-slurp
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Build
        run: cargo build --verbose
        
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

  
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/hprof-slurp.exe
          asset_name: hprof-slurp.exe
          tag: ${{ github.ref }}

